### PR TITLE
Do not update the bound value on connection

### PR DESCRIPTION
**Pull request by alshakero**
Hi! This is a PR for #141. 

Thanks

### CODE REVIEW

**Comment by e111077** [comment]
Hello, I have a few notes:

I can't seem to reproduce the issue. the jsbin does not seem to run properly, also I fear that this is a large breaking change. Also, I believe this was an intentional change for polymer 1 migration backwards compatibility.

Finally, please run the format script so that the tests can run.

**Comment by alshakero** [comment]
Hi! 

I fixed the JSBin and it's reproduced now. But I can't run `npm run format` command. It fails using `npm` and `yarn`. Windows and Linux. 

The error is:
```
$ npm run format

> @polymer/iron-input@ format C:\Work\Starcounter\iron-input
> webmat && npm run update-types


> @polymer/iron-input@ update-types C:\Work\Starcounter\iron-input
> bower install && gen-typescript-declarations --deleteExisting --outDir .

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewFixedArray
 5: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::IsKey
 6: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::IsKey
 7: v8::internal::StringTable::LookupString
 8: v8::internal::StringTable::LookupString
 9: v8::internal::SourcePositionTableIterator::Advance
10: v8::internal::SourcePositionTableIterator::Advance
11: 000003527A0843C1
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @polymer/iron-input@ update-types: `bower install && gen-typescript-declarations --deleteExisting --outDir .`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the @polymer/iron-input@ update-types script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\omer\AppData\Roaming\npm-cache\_logs\2018-12-03T11_15_56_758Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! @polymer/iron-input@ format: `webmat && npm run update-types`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the @polymer/iron-input@ format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\omer\AppData\Roaming\npm-cache\_logs\2018-12-03T11_15_56_780Z-debug.log
```

Worth mentioning that it works on `master` but not on `2.x` branch.

**Comment by e111077** [comment]
You can manually do the format as well; the diff should be in the travis failure. The error seems to be related to updating the typescript types, but this PR doesn't look like it will change them.

I am going to have to take a longer look at this as this is a breaking change and as I'm in the middle of a large internal migration of this element.

**Comment by e111077** [comment]
This is still in the process. Progress is unfortunately slow due to huge refactors in paper-input

**Pull request closed without merging**
