### PR TITLE
owners.MD writeup

### PR DESCRIPTION
**Pull request by notwaldorf**
@tjsavage @cdata WDYT? I've also added a slightly "yay! contributions" positive note.

(the contributing.md change would have to go in tedium, this is just to ...envision the future)

### CODE REVIEW

**Comment by MeTaNoV** [comment]
ohhhhhhhhhhhhh YEAH! :)

**Comment by notwaldorf** [comment]
@cdata @tjsavage Should I add a note about the process, maybe? Something about what the labels mean / how we assign things (like in https://github.com/atom/atom/blob/master/CONTRIBUTING.md)

**Comment by abdonrd** [comment]
Yeah!

**Comment by notwaldorf** [comment]
Closing and re-opening in the right repo, because i'm a dummy.

**Pull request closed without merging**
