### PR TITLE
issue with invalid property not setted correctly if type is email aft…

### PR DESCRIPTION
**Pull request by wilbiga**
…er error

if i have an element like:
&lt;input id="test-invalid" type="email" is="iron-input" invalid="{{invalid}}" /&gt;
and i type a wrong email the invalid property is false as expected.
Then if i clear the field then call validate method, the result is true and the invalid property remain true.

### CODE REVIEW

**Comment by wilbiga** [comment]
I signed it!

2015-06-01 0:46 GMT+02:00 googlebot <notifications@github.com>:

**Comment by notwaldorf** [comment]
Good catch! Thanks for the contribution!

Would you mind squashing your commits before I merge this, please? Thanks!

**Comment by wilbiga** [comment]
i have squashed my commits.

**Comment by notwaldorf** [comment]
Blerg. Something changed under you, I'm afraid, and you need to rebase :(

**Comment by wilbiga** [comment]
ok i have rebased the branch.

**Comment by notwaldorf** [comment]
Thanks! :gem:

**Pull request merged**
